### PR TITLE
A few improvements

### PR DESCRIPTION
**Pull request by tkburbidge**
- Better slider dragging.
- Ruler improvements.
- New delegate method

### CODE REVIEW

**Comment by itsmeichigo** [comment]
This seems pretty cool. But why do we need to make the trimmer view clip to bounds? It clips off the top of the tracking view and that doesn't look so nice.

**Comment by tkburbidge** [comment]
That's true, I do think it would be nice if the tracking view extended above the frames. I didn't like the black background extending beyond the sides of the trimmer view frame, though. Maybe there is a way to allow the tracker to extend but not the background.

Trevor Burbidge

On Feb 20, 2017, at 8:08 PM, Huong Do <notifications@github.com<mailto:notifications@github.com>> wrote:


This seems pretty cool. But why do we need to make the trimmer view clip to bounds? It clips off the top of the tracking view and that doesn't look so nice.

**Comment by itsmeichigo** [comment]
Perhaps there should be a `backgroundColor` property just so we can change the black color to any color to match the background and no need to clip the trimmer view.

**Comment by tkburbidge** [comment]
I just pushed a fix that clips the sides of the trimmer view but allows for the tracker view to extend above and below.

**Pull request merged**
